-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 17:17:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controle_frota
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controle_frota
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controle_frota` DEFAULT CHARACTER SET utf8 ;
USE `controle_frota` ;

-- -----------------------------------------------------
-- Table `controle_frota`.`tipo_combustivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`tipo_combustivel` (
  `idtipo_combustivel` INT NOT NULL AUTO_INCREMENT,
  `nome_combustivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_combustivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`fabricante_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`fabricante_veiculo` (
  `idfabricante_veiculo` INT NOT NULL AUTO_INCREMENT,
  `nome_fabricante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfabricante_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`modelo_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`modelo_veiculo` (
  `idmodelo_veiculo` INT NOT NULL,
  `fabricante_veiculo_idfabricante_veiculo` INT NOT NULL,
  `nome_modelo` VARCHAR(45) NOT NULL,
  `tipo_veiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmodelo_veiculo`),
  INDEX `fk_modelo_veiculo_fabricante_veiculo1_idx` (`fabricante_veiculo_idfabricante_veiculo` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_veiculo_fabricante_veiculo1`
    FOREIGN KEY (`fabricante_veiculo_idfabricante_veiculo`)
    REFERENCES `controle_frota`.`fabricante_veiculo` (`idfabricante_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `modelo_veiculo_idmodelo_veiculo` INT NOT NULL,
  `ano_fabricacao` YEAR NOT NULL,
  `ano_modelo` YEAR NOT NULL,
  `cor` INT NOT NULL,
  `num_portas` INT NOT NULL,
  `chassis` VARCHAR(60) NOT NULL,
  `placa` VARCHAR(60) NOT NULL,
  `combustivel` VARCHAR(60) NOT NULL,
  `obs_veiculo` TEXT NULL,
  PRIMARY KEY (`idveiculo`),
  INDEX `fk_veiculo_modelo_veiculo1_idx` (`modelo_veiculo_idmodelo_veiculo` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_modelo_veiculo1`
    FOREIGN KEY (`modelo_veiculo_idmodelo_veiculo`)
    REFERENCES `controle_frota`.`modelo_veiculo` (`idmodelo_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`veiculo_tipo_combustivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`veiculo_tipo_combustivel` (
  `combustivel_idtipo_combustivel` INT NOT NULL,
  `veiculo_idveiculo` INT NOT NULL,
  PRIMARY KEY (`combustivel_idtipo_combustivel`, `veiculo_idveiculo`),
  INDEX `fk_tipo_combustivel_has_veiculo_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  INDEX `fk_tipo_combustivel_has_veiculo_tipo_combustivel_idx` (`combustivel_idtipo_combustivel` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_combustivel_has_veiculo_tipo_combustivel`
    FOREIGN KEY (`combustivel_idtipo_combustivel`)
    REFERENCES `controle_frota`.`tipo_combustivel` (`idtipo_combustivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_combustivel_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `controle_frota`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `desc_estado` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `desc_cidade` VARCHAR(45) NOT NULL,
  `estado_idestado` INT NOT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `fk_cidade_estado1_idx` (`estado_idestado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `controle_frota`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`bairro_cid_uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`bairro_cid_uf` (
  `idbairro_cid_uf` INT NOT NULL AUTO_INCREMENT,
  `desc_bairro` VARCHAR(45) NOT NULL,
  `cidade_idcidade` INT NOT NULL,
  PRIMARY KEY (`idbairro_cid_uf`),
  INDEX `fk_bairro_cid_uf_cidade1_idx` (`cidade_idcidade` ASC) VISIBLE,
  CONSTRAINT `fk_bairro_cid_uf_cidade1`
    FOREIGN KEY (`cidade_idcidade`)
    REFERENCES `controle_frota`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`motorista` (
  `idmotorista` INT NOT NULL AUTO_INCREMENT,
  `nome_motorista` VARCHAR(60) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cnh` VARCHAR(11) NULL,
  `contato_celular` VARCHAR(15) NULL,
  `idbairro_cid_uf` INT NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `obs_motorista` TEXT NULL,
  PRIMARY KEY (`idmotorista`),
  INDEX `fk_motorista_bairro_cid_uf1_idx` (`idbairro_cid_uf` ASC) VISIBLE,
  CONSTRAINT `fk_motorista_bairro_cid_uf1`
    FOREIGN KEY (`idbairro_cid_uf`)
    REFERENCES `controle_frota`.`bairro_cid_uf` (`idbairro_cid_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`local_chegada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`local_chegada` (
  `idlocal_chegada` INT NOT NULL AUTO_INCREMENT,
  `desc_local_chegada` VARCHAR(45) NOT NULL,
  `idbairro_cid_uf` INT NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idlocal_chegada`),
  INDEX `fk_local_chegada_bairro_cid_uf1_idx` (`idbairro_cid_uf` ASC) VISIBLE,
  CONSTRAINT `fk_local_chegada_bairro_cid_uf1`
    FOREIGN KEY (`idbairro_cid_uf`)
    REFERENCES `controle_frota`.`bairro_cid_uf` (`idbairro_cid_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`posto_abastecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`posto_abastecimento` (
  `idposto_abastecimento` INT NOT NULL AUTO_INCREMENT,
  `nome_posto_abastecimento` VARCHAR(45) NOT NULL,
  `cnpj_posto_abastecimento` VARCHAR(45) NOT NULL,
  `idbairro_cid_uf` INT NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bandeira` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idposto_abastecimento`),
  INDEX `fk_posto_abastecimento_bairro_cid_uf1_idx` (`idbairro_cid_uf` ASC) VISIBLE,
  CONSTRAINT `fk_posto_abastecimento_bairro_cid_uf1`
    FOREIGN KEY (`idbairro_cid_uf`)
    REFERENCES `controle_frota`.`bairro_cid_uf` (`idbairro_cid_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_frota`.`controle_entrega_abastecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_frota`.`controle_entrega_abastecimento` (
  `idcontrole_entrega_abastecimento` INT NOT NULL AUTO_INCREMENT,
  `veiculo_idveiculo` INT NOT NULL,
  `motorista_idmotorista` INT NOT NULL,
  `odometro_km` INT NOT NULL,
  `local_partida` VARCHAR(60) NOT NULL,
  `data_hora_saida` DATETIME NOT NULL,
  `distancia_km` INT NULL,
  `controle_entrega_abastecimentocol` VARCHAR(45) NULL,
  `idlocal_chegada` INT NOT NULL,
  `data_hora_chegada` DATETIME NULL,
  `idposto_abastecimento` INT NOT NULL,
  `data_hora_abastecimento` DATETIME NULL,
  `tipo_combustivel` VARCHAR(60) NULL,
  `quantidade_combustivel` INT NULL,
  `valor_litro` DOUBLE NULL,
  `tanque_cheio` TINYINT NULL,
  `obs_veiculo` TEXT NULL,
  `controle_entrega_abastecimentocol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontrole_entrega_abastecimento`),
  INDEX `fk_controle_entrega_abastecimento_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  INDEX `fk_controle_entrega_abastecimento_motorista1_idx` (`motorista_idmotorista` ASC) VISIBLE,
  INDEX `fk_controle_entrega_abastecimento_local_chegada1_idx` (`idlocal_chegada` ASC) VISIBLE,
  INDEX `fk_controle_entrega_abastecimento_posto_abastecimento1_idx` (`idposto_abastecimento` ASC) VISIBLE,
  CONSTRAINT `fk_controle_entrega_abastecimento_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `controle_frota`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controle_entrega_abastecimento_motorista1`
    FOREIGN KEY (`motorista_idmotorista`)
    REFERENCES `controle_frota`.`motorista` (`idmotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controle_entrega_abastecimento_local_chegada1`
    FOREIGN KEY (`idlocal_chegada`)
    REFERENCES `controle_frota`.`local_chegada` (`idlocal_chegada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controle_entrega_abastecimento_posto_abastecimento1`
    FOREIGN KEY (`idposto_abastecimento`)
    REFERENCES `controle_frota`.`posto_abastecimento` (`idposto_abastecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
